version: '2.24'
services:
   db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

   java-app:
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - db
      ports:
       - "9090:9090"
      environment:
        DATABASE_URL: jdbc:postgresql://db:5432/auth
        DATABASE_USER: admin
        DATABASE_PASSWORD: admin

volumes:
  pgdata:
